FROM alpine:3.5

RUN apk add --update-cache py2-pip ca-certificates py2-certifi py2-lxml \
                           python-dev cython cython-dev libusb-dev build-base \
                           eudev-dev linux-headers libffi-dev

ADD . /build/
RUN pip install -e /build/[u2f]

ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
ENTRYPOINT ["aws-google-auth"]

